// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArcxvdLDbAcURIe_QCCIQRHhLfIDwGx4w',
    appId: '1:109821187558:web:d43d9b9af0ad743bdb7227',
    messagingSenderId: '109821187558',
    projectId: 'chat-app-7199c',
    authDomain: 'chat-app-7199c.firebaseapp.com',
    storageBucket: 'chat-app-7199c.appspot.com',
    measurementId: 'G-F36P7C9E98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcppXXzpqyrjj64zP00sJH1Xi3aCl19h0',
    appId: '1:109821187558:android:c466275ba4adc197db7227',
    messagingSenderId: '109821187558',
    projectId: 'chat-app-7199c',
    storageBucket: 'chat-app-7199c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNrNq5vYRGfaBsD2B63MjVKqjA7M5PWA',
    appId: '1:109821187558:ios:c66b256b3f47db72db7227',
    messagingSenderId: '109821187558',
    projectId: 'chat-app-7199c',
    storageBucket: 'chat-app-7199c.appspot.com',
    iosClientId: '109821187558-bfs80nvin2kng8cn20djlffvaknp8u6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlNrNq5vYRGfaBsD2B63MjVKqjA7M5PWA',
    appId: '1:109821187558:ios:934673d0b663af35db7227',
    messagingSenderId: '109821187558',
    projectId: 'chat-app-7199c',
    storageBucket: 'chat-app-7199c.appspot.com',
    iosClientId: '109821187558-tvu2snodl34o5vvpikbvtgvk2qte8lni.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
